version: 2

models:
    - name: ALTC_SALES_BRANDS
      description: "A dbt model that creates KPI aggregation table to monitor Sales across Brands"
      columns:
          - name: BRANDID
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
            
            
    - name: ALTC_PRODUCT_PROFITABILITY
      description: "A dbt model that creates KPI aggregation table to monitor Product profitability"
      columns:
          - name: PRODUCTID
            description: "The primary key for this table"
            tests:
                - unique
                - not_null



    - name: ALTC_BRAND
      description: "A dbt model that creates ALTC_BRAND table from the Brand table"
      columns:
          - name: BRANDID
            description: "The primary key for this table"
            

    - name: ALTC_CITY
      description: "A dbt model that creates INCR_CITY table from the City table"
      columns:
          - name: CITYID
            description: "The primary key for this table"
            
  